spring:
  application:
    name: springcloud-order-service
  main:
    allow-bean-definition-overriding: true

server:
  port: 53021
  servlet:
    context-path: /order

eureka:
  client:
    service-url:
      defaultZone: http://localhost:53000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env