spring:
  elasticsearch:
    rest:
      uris: ${haiya.elasticsearch.uris}
      username: ${haiya.elasticsearch.username}
      password: ${haiya.elasticsearch.password}

haiya:
  indices:
    show: sys-log-*,mysql-slowlog-*,sys_user,point-log-*,audit-log-*
  swagger:
    enabled: true
    title: 搜索中心
    description: 搜索中心接口文档
    version: 1.0
    base-package: com.haiya.search.controller