spring:
  application:
    name: haiya-zuul-gc-demo
  main:
    allow-bean-definition-overriding: true
server:
  port: 53010

logging:
  level:
    root: info
    org:
      springframework: info
zuul:
  retryable: true
  ignored-services: "*"
  add-host-header: true
  sensitive-headers: "*"

  routes:
    uaa:
      stripPrefix: false
      service-id: uaa-server-adv
      path: /uaa/**
    order:
      stripPrefix: false
      service-id: springcloud-order-service
      path: /order/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:53000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048
    response:
      enabled: true