server:
  port: 8080
  servlet:
    context-path: /springboot-security
spring:
  application:
    name: springboot-security-jdbc
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_learning?useUnicode=true
    username: learning
    password: Lear@2021
    driver-class-name: com.mysql.cj.jdbc.Driver