spring:
  datasource:
    url: jdbc:mysql://${haiya.datasource.ip}:3306/user-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${haiya.datasource.username}
    password: ${haiya.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

# 审计日志
haiya:
  audit-log:
    log-type: db
    enabled: true
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${haiya.datasource.ip}:3306/logger-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: ${haiya.datasource.username}
      password: ${haiya.datasource.password}